name: ✨ Feature Request
description: Displaying of all the symbols which we have in our library.
title: "[Feature Request]: Displaying of all the symbols which we have in our library"
body:
  - type: checkboxes
    id: existing-issue
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for this feature.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Please provide a detailed description of the feature you are requesting.
      placeholder: Describe the new feature or enhancement you'd like to see.
    validations:
      required: true
    value: |
      We would like to implement a feature that displays all cryptocurrency symbols available in our library. This will allow users to easily browse and select the cryptocurrency they are interested in without needing to know the symbol beforehand. The symbols should be displayed in a user-friendly format, possibly including the full name and abbreviation (e.g., Bitcoin (BTC)).
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this feature enhance your use of the project?
      placeholder: Describe a specific use case or scenario where this feature would be beneficial.
    validations:
      required: true
    value: |
      This feature would enhance user experience by helping them quickly find and select the cryptocurrency they are looking for, even if they do not know the symbol. It makes navigation more intuitive and streamlines the interaction with the system.
  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What benefits would this feature bring to the project or community?
      placeholder: Explain the advantages of implementing this feature.
    value: |
      The primary benefit is improving the user interface and overall experience by providing easier navigation and search capabilities. Users will be able to make selections faster, leading to more efficient interactions and potentially increasing usage of the system.
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - High
        - Medium
        - Low
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Record
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: yes
        - label: "I'm a GSSOC contributor"
          required: yes
        - label: "I want to work on this issue"
          required: yes
        - label: "I'm willing to provide further clarification or assistance if needed."
          required: yes
